### ISSUE TITLE
Code issues

### ISSUE THREAD

**Issue by denizsincar29** [LelsersLasers/Othello#1]
Hello! I was recently looking the part of the code of othello.
I have a few questions:
Why don't you use bitboards for the game? AI will be much faster on bitwise than on rust's structures and enums.
For AI, you can use the alpha beta algorithm that is fast and the best.
Didn't I understand something, or what are the benefits of this repo and other othello ai's written in rust?
E.g. i found this one: https://github.com/ReconGit/rust-othello-ai
Thank you

**Comment by LelsersLasers** [comment]
You are not misunderstanding anything! There is no real reason to use this repo over others. This repo was mainly a small personal project to help me learn/become more familiar with Rust!
